### ISSUE TITLE
Find usernames automatically (read, then put into variable for use by remainder of script)

### ISSUE THREAD

**Issue by matthewmccullough** [randomecho/ironing-board#2]
I think we can find the user list from the "has entered the room" lines.

**Comment by randomecho** [comment]
That will work when the transcript dump starts before anyone joins the room. Came across a couple (and of course can't find them now (couldn't find any transcripts now)) where a few users are already "hi"-ing each other before the first sign of late comers "has entered the room". Just thinking about how, if, that should be accounted for where they might be missed.
